### ISSUE TITLE
Sizing on Mobile is a little sketch..!

### ISSUE THREAD

**Issue by Aedan46206** [SecureSpark/OSSW#1]
So, I installed the OSSW earlier today. I got to say it's going to need more work, but I'll give you slack seeing how you are the only one developing this! Anyways, I installed it and I got to OSSW.html and (local-hosted) connected to the iP of my server and saw that the sizing is a little off. Don't know if this classifies as a bug? Anyways, hope this helps! 👍 Good Job With the website project and can't wait to see the new changes that will come along!

**Comment by Aedan46206** [comment]
Oh, forgot, I connected from my iPhone SE (2020)

**Comment by SecureSpark** [comment]
We are sorry for your inconvenience regarding the OSSW. SecureSpark will try it's best to solve this issue as of today and get back to you! Thanks for reaching out! 

OSSW Download: (https://securespark.org/ossw/download)  OSSW Survey: (https://securespark.org/ossw/survey)

**Comment by SecureSpark** [comment]
Okay! We've come up with a solution! We don't know what version of the OSSW you are currently running. Anyways, try inputting this code: This will hopefully fix your mobile optimization issues. Please email us if the issue continues to exist. Email: website@securespark.org Website: (https://securespark.org)



<meta name="viewport" content ="width=device-width,initial-scale=1,user-scalable=yes" />

**Comment by SecureSpark** [comment]
Here's the code:

<meta name="viewport" content ="width=device-width,initial-scale=1,user-scalable=yes" />

**Comment by SecureSpark** [comment]
You can find the code posted on this website: (https://securespark.org/ossw/code/fixes)
